name: Deploy App APK on GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Keystore
        run: |
          mkdir -p ~/keystores
          echo ${{ secrets.KEY_STORE }} | base64 --decode > android/app/publish_store.jks

      - name: Set up key.properties
        run: |
          echo "storeFile=${{ secrets.KEYSTORE_PATH }}" >> android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Archive APK
        run: mkdir -p release && cp build/app/outputs/flutter-apk/app-release.apk release/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Vérifie le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Télécharge l'APK depuis l'étape précédente
      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/app-release.apk
          token: ${{ secrets.TOKEN }}
          name: "Flutter TEST Release"
          body: |
            Ceci est un test de déploiement d'APK sur GitHub Releases.


