name: Quality Check

on:
  push:
    branches:
      - main
      - dev
      - feat/*
      - refactor/*
      - fix/*
      - chore/*
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:3.24.2 # Use a pre-built Flutter Docker image, you can specify a tag if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
